### ISSUE TITLE
Commands are wrapped at the hyphen/dash (-) when wrapping is not necessary

### ISSUE THREAD

**Issue by mpittman-netapp** [NetAppDocs/ontap#816] opened 2023-02-21 22:10 UTC
Page: [Commands for managing SMB share access control lists](https://docs.netapp.com/us-en/ontap/smb-admin/commands-manage-share-acls-reference.html)

Although the formatting of the page appears to be fine from what I can tell, even in a maximized window the second column is not expanding to fit the entire command and causing it to be wrapped like below, possibly due to the hyphen in the commands:
"vserver cifs share access-
control create"

AsciiDoc Syntax has some examples of how to adjust the column widths, but the changes I attempt in the online editor seem to break the table completely, so I did not want to submit a Pull Request with a possible change.  With this, I am hoping you all have encountered this elsewhere and have a fix that can be applied, or at least have better access to try the different options that are available to determine what works best.

**Comment by netapp-aherbin** [comment] 2023-02-22 15:32
We'll investigate this issue.  Thank you.

**Comment by ntap-bmegan** [comment] 2023-02-22 15:36
@mpittman-netapp - @netapp-aherbin contacted me about this issue because what you describe - the content of column 2 wrapping even in a maximized window - should not be possible. In my initial testing line wrap is as expected on my desktop systems -wraps or doesn't as I resize the window. Can I get your browser, OS, and general device info? Like: 

- Chrome, Windows 11, laptop 
- Safari, iOS, iPad (wide)

This will help us try to reproduce the condition you describe. 

A screenshot would also be useful.

**Comment by ntap-bmegan** [comment] 2023-02-22 16:05
Reference screenshots. Display is 1920x1080. Browser is Chrome. OS is Windows 11

![image](https://user-images.githubusercontent.com/56453501/220682975-9bbaea6f-1216-421d-b51a-02ad43871b53.png)

1. Window is full screen, shows the RD desktop layout
2. Window is just narrow enough to trigger the RD mobile layout
3. Window just wide enough to retain the RD desktop layout
4. Window just narrow enough to switch to the RD tablet layout

**Comment by mpittman-netapp** [comment] 2023-02-22 16:50
OS: Windows 10
Resolution: 1920x1080 (100% scale)
Browsers:
Firefox 110.0 (64-bit)
Chrome Version 110.0.5481.104 (Official Build) (64-bit)
Edge Version 110.0.1587.50 (Official build) (64-bit)

This issue seems to be isolated to Firefox at this point.  I was fairly certain that both Firefox and Chrome were having the issue yesterday when I submitted this issue, but I only seeing the issue in Firefox today.  I updated Firefox this morning, but that did not resolve the issue.  I also tested with Edge today and it appears to display properly there.
![mpittman_2023-02-22_Firefox](https://user-images.githubusercontent.com/86311789/220694464-8cd1b7d0-65c1-45a6-9ecf-5f12e5f56474.png)
![mpittman_2023-02-22_Chrome](https://user-images.githubusercontent.com/86311789/220694465-5082c890-0eb4-464e-9bd8-80ad3d558038.png)
![mpittman_2023-02-22_Edge](https://user-images.githubusercontent.com/86311789/220694482-46b46e8c-0641-4d92-b04e-4088a0f9341d.png)

**Comment by ntap-bmegan** [comment] 2023-02-22 17:05
Thanks, @mpittman-netapp! I've also confirmed that it's a problem on Firefox on Mac. Safari (Mac and iPad) work as expected. 

I'll open a development issue to look into the CSS. 

I'm testing a change to the heading that will give 1/3 of the table width to c1 and 2/3 to c2, but that's more a matter of a possible recommendation for table design. No browser should  interpret the table this way, so that needs to be investigated and resolved.

**Comment by ntap-bmegan** [comment] 2023-02-22 17:52
@mpittman-netapp, I'm going to close this issue since it's not a content issue and there's nothing that the writers can do. I've opened a development issue to investigate and correct the table handling discrepancy across browsers.

**Closed by ntap-bmegan** 2023-02-22 17:52 UTC
